### ISSUE TITLE
Definición de links en Menú principal

### ISSUE THREAD

**Issue by josegatica** [josegatica/parrotsec-es#1]
Sería bueno hacer propuestas acerca de qué mantenemos, borramos o agregamos al menú principal. Fijo, quiero incluir un link que redirija a una sub-página que tenga horarios de tutoriales por ejemplo.
Estoy atento a sugerencias :smile:

**Comment by netpanda** [comment]
Ok. Ahora es:

- Home
- Features
- Downloads
- News
- Documentation
- Community
- Dev Portal
- Partners
- Donations
- Join
- F.A.Q
- EDIT

Teniendo en cuenta que es la pagina de la comunidad y no la oficial, de ahi yo conservaria:

- Inicio
- Descargas
- Noticias
- Comunidad
- F.A.Q

Y agregaria. 

Eventos

**Comment by josegatica** [comment]
Me parece bien. Pensaba en algo muy similar, además de un link directo a la web oficial de Parrot, pero en el footer. No se si les parece.

**Comment by josegatica** [comment]
Hecho. Eso sí, mantuve el link Documentación porque tendremos también la propia. Ahora linkeo hacia el futuro link
